### ISSUE TITLE
Missing Review for HW Wallets

### ISSUE THREAD

**Issue by maaxaam** [bitfalls/bitfalls_content#1]
Trezor i Nano Ledger Blue. On purpose as Nano Ledger S i selling on the website or there is other reasons... :)

Max

**Comment by Swader** [comment]
Other reason: I do not have a Trezor or Blue :D 
The current post is not a review anyway, just an explanation of how the wallet works. Am open to explanations of how others work, too, if different from Nano S.

**Comment by maaxaam** [comment]
I'm planning to buy Trezor, will let you know once it surmounts to more then a plan. :)
