### ISSUE TITLE
Translate some Bitfinexed posts

### ISSUE THREAD

**Issue by Swader** [bitfalls/bitfalls_content#12]
Bitfinexed, the guy who uncovered the Tether fraud, is okay with us republishing his posts and linking back to the original, as long as we link his twitter handle and give full attribution. A Croatian translation of some of the most important posts would be interesting. $50 in Eth per translation can be scored.

**Comment by maaxaam** [comment]
After glossary I will take a look.

**Comment by maaxaam** [comment]
https://medium.com/@bitfinexed
https://www.youtube.com/channel/UCbUsrLFoofjdKiqbQm8wVvQ

Pick the articles with most acclaim or you have a preference.

Please @Swader do confirm that indeed the resources are correct.

Thx
Max

**Comment by maaxaam** [comment]
Ok... I have read all the articles on medium link but I feel that these are all interconnected and very good. This is the list:
https://medium.com/@bitfinexed/are-fraudulent-tethers-being-used-for-margin-lending-on-bitfinex-5de9dd80f330
https://hackernoon.com/the-curious-tale-of-tethers-6b0031eead87
https://hackernoon.com/meet-spoofy-how-a-single-entity-dominates-the-price-of-bitcoin-39c711d28eb4
https://medium.com/@bitfinexed/are-legitimate-institutional-investors-really-coming-onto-bitfinex-s-platform-i-don-t-think-so-cb4ed5175092

These seem to be rebuttals and further challenges and may not be as interesting:
https://medium.com/@bitfinexed/why-wont-bitfinex-tether-publish-already-existing-audit-reports-as-they-promise-future-bitfinex-51d26d14d226
https://medium.com/@bitfinexed/a-response-to-tether-releasing-their-prior-audits-cceab8989c70

Let me know if you approve. 

Max

@Swader

**Comment by maaxaam** [comment]
done - https://medium.com/@bitfinexed/are-fraudulent-tethers-being-used-for-margin-lending-on-bitfinex-5de9dd80f330

**Comment by maaxaam** [comment]
Nastavak bi trebao ici u ovom smjeru:
https://hackernoon.com/the-curious-tale-of-tethers-6b0031eead87

pojasnjenje Tethera. 

Ok?

@Swader

**Comment by maaxaam** [comment]
Prevedeno. Ostaje jos dva koja su important. Sljedeci je:
https://hackernoon.com/meet-spoofy-how-a-single-entity-dominates-the-price-of-bitcoin-39c711d28eb4

**Comment by maaxaam** [comment]
Done. 1 more left. Samo cu ga jos jednom procitati da vidim je li uopce potreban nakon ova tri... https://medium.com/@bitfinexed/are-legitimate-institutional-investors-really-coming-onto-bitfinex-s-platform-i-don-t-think-so-cb4ed5175092
