### ISSUE TITLE
Članak Rudarenje ili investiranje u kriptovalute - opaske

### ISSUE THREAD

**Issue by matijamihic** [bitfalls/bitfalls_content#37]
Ethereum prelazi na PoS sustav rudarenja, pa jaka računala više neće imati smisla.
- ovo se uopce nezna kad ce biti ni da li - dakle ovo je špekulacija. također PoS nije "sustav rudarenja". iako ok laički može se tako reći. kad se kaze rudarenje misli se na PoW.

Nagrada za block u Ethereum sustavu se postepeno smanjuje. Sada je 5, uskoro će biti 3, kasnije će biti još manje. Redukcija od 40% nije trivijalna.
- također spekulacija - ice age je poništen jer je Pos odgođen (mozda i zauvijek tko zna ili cemo imati i pos i pow kao kod nekih coina) - a nagrada se smanjila na 3, dok se block time smanjio sa 30 na 15s. u tom trenu nagrada je ostala ista. nigje nisam vidio spomen buduceg smanjivanja nagrade, ako imas neki izvor rado bi to procitao.

Težina rudarenja se postepeno povećava kako se nagrada smanjuje – s ciljem prelaska na PoS konsenzus. To znači da strojevi ne samo dobivaju manje nagrade, nego i postaju manje efikasni u rudarenju.
-ovo nije tocno, trenutno se, u eth-u, tezina povecava samo zbog dolaska novih minera. također ovo o PoS-u je trenutno spekulacija, ali to sam vec spomenuo.

Struja košta, i može poskupiti svakog trena....
- struja je u hr socijalna kategorija, a i vani je tako nekako. nema tu velikih fluktuacija, bar ne u tim kratkim rokovima, godinu dana ili manje.

hardver može pregoriti. Grafičke kartice koje su stalno na 120% kapaciteta...
-ovo nije tocno, graficke su undervoltane i rade na 50-70% od max-a, dakle minanje cuva, stedi kartice. dual mining vise opterecuje, ali opet ne toliko, i te kartice rade puno ispod gejmerskog opterecenja, i sto je jos bitnije, na niskim temperaturama (oko 50 stupnjeva). također ventilatori su na niskim okretajima (i konstantnim) i stede se. uostalom garancija je 2-3 godine, ovisno o proizvođacu - cak i da pregori.

mislim također da su sve ove 3 "zablude" upitne i vrlo špekulativne. trenutno jest profitabilnost manja nego tijekom ljeta, ali to nista ne znaci dugorocno. taokđer mining i ulaganje su druga kategorija. ROI je trenutno na godini dana, sto nije uopce grozno - nađi mi jos par takvih prilika da investiram - pa ni kupit barku i da cijelo ljeto vozas turiste okolo je neces isplatit kad uracunas troskove i svoju satnicu, uduplavanjem cijene etha mining bi lako mogao opet postati vrlo isplativ (<6mj roi) a kremu ce pokupiti oni koji su vec u tome, tj. ubrzano ce isplatiti strojeve.

kako ja to gledam: majner je asset - ulog je kolki je i dobijas kolko dobijas povrat. to je fizički. trgovanje je s druge strane veca spekulacija.

također nije mi jasno zasto se mining proglasava nekim stresnim poslom posto jednom kad se namjeste rigovi nema oko njih nis za radit, bacit oko svaki dan kako idu, a lako se namjesti automatski reset ako prestanu majnati ili se smanji hashrate. teamview postoji. kontrola temperature također automatska. 

slazem se da je ulaganje mozda "laksa" opcija. ali pogledajmo sljedece: puno ljudi popusi na trgovanju, to je cinjenica. majnanje osigurava steady povrat - sto od prodanog polovnog hardvera - sto od izmajnanih coina - i to treba uzeti u racunicu, da ce se taj hardver kad-tad utopiti. cak i prastari asicsi imaju svoje trziste. to nigje nije spomenuto.

uglavnom slazem se da je trenutno bolja (profitabilnija) opcija investirati direktno u kripto ali mislim da moglo to i na bolji nacin objasniti, ovo malo me grize jer je tekst dosta spekulativan, a autor dosta sve to prikazuje kao činjenično.
sjetimo se da je pocetkom godine za majning situacija bila ista ko i sad ako ne i gora - a pogledajmo kolko su ti ljudi na kraju zaradili kad je doslo do boom-a. vecina je u 2-3 ljetna mjeseca zaradila (cisto od majna - da su svaki dan mijenjali izmajnano u dolare) za sve strojeve (a od vec izvađenih coina da ne spominjem profite). ako opet dodje do takvog skoka - strojeve ce (brze) isplatiti oni koji ih vec imaju i zaraditi dosta viška. najveci problem je sto i "moja baka" majna ethereum, tj dio kolača zele svi - sto je za kripto odlicno i to povecava popularnost i sirenje kripta.
Ne kazem da nisu vise zaradili oni koji su stavili u eth, ali mogla je biti situacija da eth danas i dalje recimo 100$ i majnerii bi opet vracali ulozene pare. dok neki investitor bi se zesce preznojavao jer eto ulozio je pred 3-4 mjeseca a ovo niš ne raste. jos zamislimo da se drzi iste cijene a ide gore dolje 20-30-40% u valovima kako to vec ide u kriptu. koliko bi celicnih zivaca morao biti da zadrzis taj coin? vrlo stresno.

pretpostavljam da dosta na kraju ovisi i kakav je netko i tip osobe. ja ne bi nikad slozio rig da mi sve to (hardver) nije blisko, jer da - na pocetku ima posla.

**Comment by Swader** [comment]
> ovo se uopce nezna kad ce biti ni da li - dakle ovo je špekulacija. također PoS nije "sustav rudarenja". iako ok laički može se tako reći. kad se kaze rudarenje misli se na PoW.

Jasno, ali bitno je sadržaj učiniti pristupačnim laicima. Smatram da reći da su i PoW i PoS sustavi tipovi rudarenja nije tehnički netočno, jer oba pristupa proizvode novi Eth.

> ako imas neki izvor rado bi to procitao.

Prema [ovim idejama](https://blog.ethereum.org/2016/07/27/inflation-transaction-fees-cryptocurrency-monetary-policy/).

> ovo nije tocno, trenutno se, u eth-u, tezina povecava samo zbog dolaska novih minera. također ovo o PoS-u je trenutno spekulacija, ali to sam vec spomenuo.

Krivo sam se izrazio. Htio sam reći da se oboje dešava istovremeno, ne da jedno uzrokuje drugo.

Slažem se s ostalim feedbackom, hvala, revidirat ću post prvom prilikom.
